server:
  port: 8081

spring:
  config:
    import:
      - optional:application-telegram.yml
      - optional:application-finnhub.yml
      - optional:application-marketaux.yml
  main:
    web-application-type: none

storage:
  subscriptions:
    telegram: "subscriptions/telegram-subscriptions.yml"
