server:
  port: 8081

finnhub:
  api:
    base-url: https://finnhub.io/api/v1
    token: ${FINNHUB_API_KEY}

marketaux:
  api:
    base-url: https://api.marketaux.com/v1
    token: ${MARKETAUX_API_KEY}
